import type { Gig, Lead } from '@/types';

// ─── Demo Upwork Gigs ─────────────────────────────────────────

export const DEMO_GIGS: Gig[] = [
  {
    id: 'gig-001',
    title: 'Senior React Developer for SaaS Dashboard Redesign',
    description:
      'We need an experienced React developer to redesign our analytics dashboard. The project involves building new data visualization components, improving performance, and implementing a new design system. Our current stack is React 18, TypeScript, and Tailwind CSS. We expect weekly progress updates and clean, documented code.',
    budget: { type: 'fixed', min: 2000, max: 4000, currency: 'USD' },
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Data Visualization', 'Recharts'],
    clientHistory: { totalSpent: 45000, hires: 12, rating: 4.9, reviews: 8, location: 'United States' },
    postedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    experienceLevel: 'expert',
    projectType: 'short',
    url: 'https://www.upwork.com/jobs/~example001',
    status: 'new',
    source: 'upwork',
    scrapedAt: new Date().toISOString(),
    summary: 'Client needs a React expert to modernize their SaaS analytics dashboard with better components and design system.',
    proposalAngles: ['Lead with dashboard performance wins', 'Reference SaaS dashboard case study', 'Offer design system audit'],
    likelyClientTone: 'technical',
    likelyPainPoints: ['Dashboard feels outdated', 'Performance issues', 'No consistent design system'],
    conversionScore: 8,
    recommendedStyle: 'technical',
    clientProfileSummary: 'Established SaaS company, high-value client with strong track record.',
    likelyObjections: ['Price sensitivity', 'Wanting to see prior SaaS work'],
    bestMessageAngle: "I noticed you're rebuilding your dashboard — here's what I'd do differently from day one to avoid the usual performance traps.",
  },
  {
    id: 'gig-002',
    title: 'AI Integration Specialist – OpenAI & LangChain Workflow Automation',
    description:
      'Looking for someone to build an AI-powered document processing pipeline using OpenAI GPT-4 and LangChain. The system needs to extract data from PDFs, classify documents, and route them to the correct departments. Budget is flexible for the right person. Preferred: experience with production AI systems.',
    budget: { type: 'hourly', min: 80, max: 150, currency: 'USD' },
    skills: ['OpenAI API', 'LangChain', 'Python', 'Document Processing', 'API Integration'],
    clientHistory: { totalSpent: 12000, hires: 3, rating: 4.7, reviews: 3, location: 'Germany' },
    postedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    experienceLevel: 'expert',
    projectType: 'long',
    url: 'https://www.upwork.com/jobs/~example002',
    status: 'saved',
    source: 'upwork',
    scrapedAt: new Date().toISOString(),
    summary: 'European company needs an AI specialist to build a document processing pipeline with GPT-4 and LangChain.',
    proposalAngles: ['Highlight production AI experience', 'Propose architecture overview', 'Mention cost optimization strategies'],
    likelyClientTone: 'technical',
    likelyPainPoints: ['Manual document processing bottleneck', 'Need for automation', 'Budget for quality'],
    conversionScore: 9,
    recommendedStyle: 'technical',
    clientProfileSummary: 'Mid-size European company, technically sophisticated, willing to pay for expertise.',
    likelyObjections: ['Timezone difference', 'Not sure about production readiness'],
    bestMessageAngle: "I've built production LangChain document pipelines — here's my approach for handling edge cases that break most implementations.",
  },
  {
    id: 'gig-003',
    title: 'E-commerce Product Description Writer (100+ SKUs)',
    description:
      'We need engaging, SEO-optimized product descriptions for our new clothing line. We have 120 SKUs and need descriptions that are on-brand, conversion-focused, and unique. Tone: friendly, aspirational. We have brand guidelines ready to share.',
    budget: { type: 'fixed', min: 500, max: 800, currency: 'USD' },
    skills: ['Copywriting', 'SEO', 'E-commerce', 'Content Writing'],
    clientHistory: { totalSpent: 3200, hires: 5, rating: 4.6, reviews: 4, location: 'Australia' },
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    experienceLevel: 'intermediate',
    projectType: 'short',
    url: 'https://www.upwork.com/jobs/~example003',
    status: 'new',
    source: 'upwork',
    scrapedAt: new Date().toISOString(),
    summary: 'Australian clothing brand needs conversion-focused, SEO-optimized descriptions for 120 products.',
    proposalAngles: ['Show conversion-focused writing samples', 'Mention E-commerce SEO expertise', 'Offer a free sample description'],
    likelyClientTone: 'friendly',
    likelyPainPoints: ['Generic product copy', 'Poor SEO visibility', 'Low conversion rates'],
    conversionScore: 6,
    recommendedStyle: 'friendly',
    clientProfileSummary: 'Small-medium fashion brand, creative, brand-conscious, moderate budget.',
    likelyObjections: ['Volume vs quality tradeoff', 'Understanding their brand voice'],
    bestMessageAngle: 'I write e-commerce descriptions that rank AND convert — happy to write a free sample for one of your SKUs so you can see the quality.',
  },
  {
    id: 'gig-004',
    title: 'Full-Stack Next.js Developer for B2B Marketplace MVP',
    description:
      'Building a B2B marketplace MVP. Tech stack: Next.js 14, Prisma, PostgreSQL, Stripe. Need someone who can build fast without hand-holding. The founder is technical. We want to launch in 6 weeks. Must be available for daily standups.',
    budget: { type: 'fixed', min: 5000, max: 8000, currency: 'USD' },
    skills: ['Next.js', 'PostgreSQL', 'Prisma', 'Stripe', 'TypeScript'],
    clientHistory: { totalSpent: 0, hires: 0, rating: 0, reviews: 0, location: 'United Kingdom' },
    postedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    experienceLevel: 'expert',
    projectType: 'short',
    url: 'https://www.upwork.com/jobs/~example004',
    status: 'new',
    source: 'upwork',
    scrapedAt: new Date().toISOString(),
    summary: 'UK startup founder needs an expert Next.js developer to build a B2B marketplace MVP in 6 weeks.',
    proposalAngles: ["Reference marketplace builds you've shipped", 'Address the 6-week timeline directly', 'Show you understand B2B marketplace complexity'],
    likelyClientTone: 'startup',
    likelyPainPoints: ['Need to move fast', 'First hire on Upwork (risk)', 'Technical founder wants a peer, not a vendor'],
    conversionScore: 7,
    recommendedStyle: 'technical',
    clientProfileSummary: 'First-time Upwork buyer. Technical founder, UK startup. High budget, high urgency.',
    likelyObjections: ['No Upwork history = risk', 'Timeline is ambitious'],
    bestMessageAngle: "I've shipped two B2B marketplace MVPs in Next.js — let me show you my architecture and we can decide if 6 weeks is realistic.",
  },
  {
    id: 'gig-005',
    title: 'LinkedIn Ghostwriter for B2B SaaS Founder (Weekly Posts)',
    description:
      "I'm a SaaS founder and need a skilled ghostwriter to write my LinkedIn content. I'll provide bullet points and you'll turn them into engaging posts. Looking for someone who understands B2B audience, growth mindset, and can match my voice after a brief call.",
    budget: { type: 'hourly', min: 40, max: 70, currency: 'USD' },
    skills: ['Ghostwriting', 'LinkedIn', 'Content Strategy', 'B2B Marketing'],
    clientHistory: { totalSpent: 8000, hires: 6, rating: 5.0, reviews: 5, location: 'United States' },
    postedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    experienceLevel: 'intermediate',
    projectType: 'ongoing',
    url: 'https://www.upwork.com/jobs/~example005',
    status: 'new',
    source: 'upwork',
    scrapedAt: new Date().toISOString(),
    summary: 'SaaS founder needs a reliable LinkedIn ghostwriter who can match their voice and write weekly B2B content.',
    proposalAngles: ['Share LinkedIn post examples', 'Emphasize voice-matching process', 'Offer a 2-post trial'],
    likelyClientTone: 'friendly',
    likelyPainPoints: ['Lack of time to write', 'Inconsistent posting', 'Worry about losing authentic voice'],
    conversionScore: 8,
    recommendedStyle: 'friendly',
    clientProfileSummary: 'Active Upwork buyer, 5-star history. SaaS founder who values quality and relationship.',
    likelyObjections: ['Voice mismatch', 'Reliability concern'],
    bestMessageAngle: "I ghostwrite for two other SaaS founders — after one call I can capture your voice so well your audience won't notice the difference.",
  },
];

// ─── Demo Leads ──────────────────────────────────────────────

export const DEMO_LEADS: Lead[] = [
  {
    id: 'lead-001',
    name: 'Sarah Chen',
    company: 'NexaScale',
    role: 'Co-founder & CEO',
    niche: 'B2B SaaS / HR Tech',
    location: 'San Francisco, CA',
    website: 'https://nexascale.com',
    socialLinks: [{ platform: 'linkedin', url: 'https://linkedin.com/in/sarahchen' }],
    bio: 'Building the future of employee performance management. Ex-Google. YC W23. We help companies scale their people ops. Obsessed with data-driven HR.',
    businessNeedIndicators: ['Scaling tech team', 'YC company with growth pressure', 'Hiring engineers'],
    source: 'linkedin',
    sourceUrl: 'https://linkedin.com/in/sarahchen',
    scrapedAt: new Date().toISOString(),
    status: 'new',
    summary: 'YC-backed SaaS founder scaling an HR tech platform. Ex-Google background suggests high technical standards.',
    outreachAngle: 'Reference the scaling challenges YC companies face when their people ops can\'t keep up with growth.',
    likelyPainPoints: ['Engineering team scaling bottlenecks', 'Moving fast while maintaining code quality', 'Finding reliable technical contractors'],
    suggestedOfferFraming: 'Frame as a technical partner who can ship fast without hand-holding.',
    recommendedTone: 'direct',
    communicationStyle: 'entrepreneur',
    confidenceNotes: 'High confidence: LinkedIn bio is detailed. Pain points inferred from YC stage + HR tech focus.',
    qualityScore: 9,
    businessNeedSummary: 'Likely needs technical support for fast-moving platform development given YC growth pressure.',
  },
  {
    id: 'lead-002',
    name: 'Marcus Williams',
    company: 'BlueOak Consulting',
    role: 'Managing Partner',
    niche: 'Strategy Consulting',
    location: 'Chicago, IL',
    website: 'https://blueoakconsulting.com',
    socialLinks: [{ platform: 'linkedin', url: 'https://linkedin.com/in/marcuswilliams' }],
    bio: 'Helping mid-market companies navigate digital transformation. 15 years in management consulting. Believer in practical, not theoretical, change.',
    businessNeedIndicators: ['Digital transformation focus', 'Mid-market clients', 'Building consulting practice'],
    source: 'linkedin',
    sourceUrl: 'https://linkedin.com/in/marcuswilliams',
    scrapedAt: new Date().toISOString(),
    status: 'researched',
    summary: 'Senior strategy consultant helping mid-market companies with digital transformation. Values practical outcomes.',
    outreachAngle: 'Frame around ROI and measurable outcomes for his clients — he sells this to his clients, so he\'ll respect it.',
    likelyPainPoints: ['Delivering digital projects on time', 'Finding reliable technical execution partners', 'Demonstrating ROI to clients'],
    suggestedOfferFraming: 'Position as an execution partner who makes his consulting recommendations come to life.',
    recommendedTone: 'professional',
    communicationStyle: 'executive',
    confidenceNotes: 'Medium confidence: bio is concise. Consulting firm signals = execution-focused needs.',
    qualityScore: 7,
    businessNeedSummary: 'Needs reliable technical execution partners to implement the digital strategies he sells to clients.',
  },
  {
    id: 'lead-003',
    name: 'Priya Nair',
    company: 'The Content Lab',
    role: 'Founder',
    niche: 'Content Marketing Agency',
    location: 'London, UK',
    website: 'https://thecontentlab.co',
    socialLinks: [{ platform: 'linkedin', url: 'https://linkedin.com/in/priyanair' }],
    bio: 'Agency owner helping B2B brands build thought leadership through strategic content. 8 years in content marketing. Writing about agency growth and content strategy.',
    businessNeedIndicators: ['Agency owner', 'Content-focused business', 'Scaling concern'],
    source: 'facebook',
    sourceUrl: 'https://facebook.com/thecontentlab',
    scrapedAt: new Date().toISOString(),
    status: 'new',
    summary: 'UK-based content marketing agency founder helping B2B brands. Likely needs tech, design, or process support.',
    outreachAngle: 'Reference the specific challenge of scaling a content agency without proportionally growing headcount.',
    likelyPainPoints: ['Scaling output without hiring full-time', 'Content repurposing workflows', 'Technical implementation of content strategies'],
    suggestedOfferFraming: 'Offer to be the technical arm she doesn\'t have in-house.',
    recommendedTone: 'friendly',
    communicationStyle: 'entrepreneur',
    confidenceNotes: 'Medium confidence: agency focus and "scaling" language suggest operational needs.',
    qualityScore: 6,
    businessNeedSummary: 'Content agency founder who likely needs technical or design support to scale without bloating headcount.',
  },
  {
    id: 'lead-004',
    name: 'David Park',
    company: 'TechFlow AI',
    role: 'Head of Product',
    niche: 'Enterprise AI / ML Platform',
    location: 'Austin, TX',
    website: 'https://techflowai.com',
    socialLinks: [{ platform: 'linkedin', url: 'https://linkedin.com/in/davidpark' }],
    bio: 'Building AI products that actually ship. Previously at Stripe and Notion. Focused on making ML accessible to non-technical teams. Writing about product-led growth.',
    businessNeedIndicators: ['AI product focus', 'PLG interested', 'Ex-top company'],
    source: 'linkedin',
    sourceUrl: 'https://linkedin.com/in/davidpark',
    scrapedAt: new Date().toISOString(),
    status: 'outreach_sent',
    summary: 'Experienced product leader at AI startup. Stripe/Notion background signals high standards and fast-paced environment.',
    outreachAngle: 'Reference PLG product challenges — specifically the gap between ML capability and user adoption.',
    likelyPainPoints: ['Getting non-technical users to adopt AI features', 'Product-led growth for complex AI products', 'Contractor reliability at this level'],
    suggestedOfferFraming: 'Position around shipping, not just building — Stripe/Notion alum will value execution speed.',
    recommendedTone: 'direct',
    communicationStyle: 'technical',
    confidenceNotes: 'High confidence: Rich profile, clear track record. Pain points are well-signaled.',
    qualityScore: 9,
    businessNeedSummary: 'Needs high-quality technical or product execution support at a level matching his top-company background.',
  },
];

// ─── Demo Activity ────────────────────────────────────────────

export const DEMO_ACTIVITY = [
  {
    id: 'act-001',
    type: 'gig_scraped' as const,
    title: '5 new Upwork gigs found',
    description: 'React Developer, AI Integration, E-commerce Writer and 2 more',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-002',
    type: 'proposal_generated' as const,
    title: 'Proposal generated for "Senior React Developer"',
    description: 'Generated with Gemini → Claude pipeline (Premium style)',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-003',
    type: 'lead_found' as const,
    title: '4 new LinkedIn leads discovered',
    description: 'Sarah Chen, Marcus Williams, Priya Nair, David Park',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-004',
    type: 'outreach_sent' as const,
    title: 'Outreach sent to David Park',
    description: 'First message via LinkedIn DM (Direct tone)',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-005',
    type: 'feedback_received' as const,
    title: 'Positive feedback on proposal',
    description: 'Gemini→Claude pipeline rated 5/5 for React Developer gig',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
];
